/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Usuario
 */
public class FrmLogin extends javax.swing.JFrame {
    
    private char caracterContrasena;
    
    

    /**
     * Creates new form FrmLogin
     */
    public FrmLogin() {
    initComponents();

    utilidades.EstilosComponentes
            .aplicarCampoUsuario(txtUsuario);

    utilidades.EstilosComponentes
            .aplicarCampoContrasena(txtContrasena);

    utilidades.EstilosComponentes
            .aplicarBotonPrimario(btnIngresar);

    caracterContrasena = txtContrasena.getEchoChar();

    setIconImage(
            new javax.swing.ImageIcon(
                    getClass().getResource(
                            "/recursos/gymnova_logo_gn_32.png"
                    )
            ).getImage()
    );

    getRootPane().setDefaultButton(btnIngresar);

    utilidades.AyudasContextuales.aplicar(getContentPane());
    txtUsuario.setToolTipText(
            "Ingrese el alias de usuario asignado a su cuenta."
    );
    txtContrasena.setToolTipText(
            "Ingrese su contrasena. Se bloqueara temporalmente tras varios intentos fallidos."
    );

    pnlFondo.setComponentZOrder(
            lblFondoGimnasio,
            pnlFondo.getComponentCount() - 1
    );

    setLocationRelativeTo(null);
    setResizable(false);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        lblFondoGimnasio = new javax.swing.JLabel();
        pnlMarca = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblGymnova = new javax.swing.JLabel();
        lblLema = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblSubLema = new javax.swing.JLabel();
        pnlAcceso = new javax.swing.JPanel();
        lblTituloLogin = new javax.swing.JLabel();
        lblSubtituloLogin = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblContrasena = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JPasswordField();
        chkMostrarContrasena = new javax.swing.JCheckBox();
        btnIngresar = new javax.swing.JButton();
        lblMensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GYMNOVA - Iniciar sesión");
        setResizable(false);

        pnlFondo.setBackground(new java.awt.Color(5, 15, 32));

        lblFondoGimnasio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFondoGimnasio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/gymnova_fondo_login.png"))); // NOI18N

        pnlMarca.setOpaque(false);
        pnlMarca.setPreferredSize(new java.awt.Dimension(430, 500));

        lblLogo.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        lblLogo.setForeground(new java.awt.Color(255, 255, 255));
        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/gymnova_logo_gn_256.png"))); // NOI18N

        lblGymnova.setFont(new java.awt.Font("SansSerif", 1, 32)); // NOI18N
        lblGymnova.setForeground(new java.awt.Color(255, 255, 255));
        lblGymnova.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGymnova.setText("GYMNOVA");
        lblGymnova.setToolTipText("");
        lblGymnova.setPreferredSize(new java.awt.Dimension(250, 40));

        lblLema.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        lblLema.setForeground(new java.awt.Color(220, 235, 255));
        lblLema.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLema.setText("El control de tu gimnasio");
        lblLema.setToolTipText("");
        lblLema.setPreferredSize(new java.awt.Dimension(390, 35));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(220, 235, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("en un solo lugar.");

        lblSubLema.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        lblSubLema.setForeground(new java.awt.Color(220, 235, 255));
        lblSubLema.setText("<html><center>Gestiona socios, rutinas, ventas<br>y mucho más desde un solo lugar</center></html>");
        lblSubLema.setPreferredSize(new java.awt.Dimension(390, 35));

        javax.swing.GroupLayout pnlMarcaLayout = new javax.swing.GroupLayout(pnlMarca);
        pnlMarca.setLayout(pnlMarcaLayout);
        pnlMarcaLayout.setHorizontalGroup(
            pnlMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMarcaLayout.createSequentialGroup()
                .addGroup(pnlMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMarcaLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(pnlMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lblLogo)
                            .addComponent(lblGymnova, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLema, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlMarcaLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(pnlMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSubLema, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pnlMarcaLayout.setVerticalGroup(
            pnlMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMarcaLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblLogo)
                .addGap(12, 12, 12)
                .addComponent(lblGymnova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblSubLema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pnlAcceso.setBackground(new java.awt.Color(11, 24, 48));
        pnlAcceso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(8, 124, 255)));
        pnlAcceso.setPreferredSize(new java.awt.Dimension(400, 500));

        lblTituloLogin.setFont(new java.awt.Font("SansSerif", 1, 26)); // NOI18N
        lblTituloLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloLogin.setText("Iniciar sesión");
        lblTituloLogin.setPreferredSize(new java.awt.Dimension(300, 38));

        lblSubtituloLogin.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblSubtituloLogin.setForeground(new java.awt.Color(157, 184, 216));
        lblSubtituloLogin.setText("Ingresa tus credenciales para continuar");
        lblSubtituloLogin.setPreferredSize(new java.awt.Dimension(300, 25));

        lblUsuario.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(220, 235, 255));
        lblUsuario.setText("Usuario");

        txtUsuario.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtUsuario.setPreferredSize(new java.awt.Dimension(300, 38));

        lblContrasena.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        lblContrasena.setForeground(new java.awt.Color(220, 235, 255));
        lblContrasena.setText("Contraseña");

        txtContrasena.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtContrasena.setPreferredSize(new java.awt.Dimension(300, 38));

        chkMostrarContrasena.setBackground(new java.awt.Color(11, 24, 48));
        chkMostrarContrasena.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        chkMostrarContrasena.setForeground(new java.awt.Color(199, 215, 233));
        chkMostrarContrasena.setText("Mostrar contraseña");
        chkMostrarContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMostrarContrasenaActionPerformed(evt);
            }
        });

        btnIngresar.setBackground(new java.awt.Color(8, 124, 255));
        btnIngresar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresar.setText("INGRESAR");
        btnIngresar.setFocusPainted(false);
        btnIngresar.setPreferredSize(new java.awt.Dimension(300, 42));
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        lblMensaje.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblMensaje.setForeground(new java.awt.Color(255, 23, 68));
        lblMensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMensaje.setPreferredSize(new java.awt.Dimension(300, 28));

        javax.swing.GroupLayout pnlAccesoLayout = new javax.swing.GroupLayout(pnlAcceso);
        pnlAcceso.setLayout(pnlAccesoLayout);
        pnlAccesoLayout.setHorizontalGroup(
            pnlAccesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAccesoLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(pnlAccesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTituloLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSubtituloLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuario)
                    .addComponent(lblContrasena)
                    .addComponent(txtContrasena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkMostrarContrasena)
                    .addComponent(btnIngresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(49, 49, 49))
        );
        pnlAccesoLayout.setVerticalGroup(
            pnlAccesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAccesoLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblTituloLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubtituloLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblContrasena)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(chkMostrarContrasena)
                .addGap(18, 18, 18)
                .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlFondoLayout = new javax.swing.GroupLayout(pnlFondo);
        pnlFondo.setLayout(pnlFondoLayout);
        pnlFondoLayout.setHorizontalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFondoGimnasio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(pnlMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(pnlAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFondoLayout.setVerticalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFondoGimnasio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkMostrarContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMostrarContrasenaActionPerformed
        // TODO add your handling code here:
        if (chkMostrarContrasena.isSelected()) {
        txtContrasena.setEchoChar((char) 0);
    } else {
        txtContrasena.setEchoChar(
                caracterContrasena
        );
    }
    }//GEN-LAST:event_chkMostrarContrasenaActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
        lblMensaje.setText("");
btnIngresar.setEnabled(false);

try {
    controlador.LoginControlador controlador
            = new controlador.LoginControlador();

    modelo.Usuario usuario
            = controlador.iniciarSesion(
                    txtUsuario.getText(),
                    txtContrasena.getPassword()
            );

    utilidades.SesionUsuario.iniciarSesion(
            usuario
    );

    FrmPrincipal principal = new FrmPrincipal();
    principal.setVisible(true);

    dispose();

} catch (IllegalArgumentException
        | IllegalStateException e) {

    lblMensaje.setText(e.getMessage());
    txtContrasena.setText("");
    txtContrasena.requestFocus();

} catch (java.sql.SQLException e) {

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "No se pudo conectar con PostgreSQL.\n"
            + "Detalle: "
            + e.getMessage(),
            "Error de conexión",
            javax.swing.JOptionPane.ERROR_MESSAGE
    );

} finally {
    btnIngresar.setEnabled(true);
}
    }//GEN-LAST:event_btnIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JCheckBox chkMostrarContrasena;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblFondoGimnasio;
    private javax.swing.JLabel lblGymnova;
    private javax.swing.JLabel lblLema;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblSubLema;
    private javax.swing.JLabel lblSubtituloLogin;
    private javax.swing.JLabel lblTituloLogin;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlAcceso;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlMarca;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
